export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
export const USER_CANNOT_CREATE = "USER_CANNOT_CREATE"
export const USER_ALREADY_CONNECTED_ANOTHER_PROVIDER =
  "USER_ALREADY_CONNECTED_ANOTHER_PROVIDER"
